// CLARITY Thermal Assessment Report — PDF Generator
// Matches CLARITY lab report styling: gold/navy/cream theme

import { jsPDF } from 'jspdf'
import {
  ThermographySession, ThermographyImage, ThermographyFinding,
  ThermographyAnnotation, VIEW_LABELS, ViewType,
} from './thermography-types'

// Colors (matching lab-patient-pdf.ts)
const PRIMARY = [26, 26, 46] as const       // #1a1a2e deep navy
const GOLD = [212, 163, 115] as const       // #d4a373
const GOLD_LIGHT = [242, 229, 213] as const
const CREAM = [254, 250, 224] as const      // #fefae0
const WHITE = [255, 255, 255] as const
const GRAY = [120, 120, 120] as const
const DARK_TEXT = [40, 40, 40] as const
const LIGHT_GRAY = [230, 230, 230] as const
const RED = [200, 40, 40] as const
const ORANGE = [224, 112, 32] as const
const SAGE = [88, 129, 87] as const

const SEVERITY_COLORS: Record<string, readonly [number, number, number]> = {
  mild: GOLD,
  moderate: ORANGE,
  significant: RED,
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

interface ReportData {
  session: ThermographySession
  images: ThermographyImage[]
  findings: ThermographyFinding[]
  annotations: ThermographyAnnotation[]
}

export function generateThermographyReport(data: ReportData): Buffer {
  const { session, images, findings, annotations } = data
  const doc = new jsPDF({ unit: 'mm', format: 'letter' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 22
  const contentW = pageW - margin * 2
  let y = 0
  let pageNum = 1

  // ── Helpers ──

  function goldLine(yPos: number, weight = 0.5) {
    doc.setDrawColor(...GOLD)
    doc.setLineWidth(weight)
    doc.line(margin, yPos, pageW - margin, yPos)
  }

  function addPageFooter(pn: number) {
    doc.setFontSize(7)
    doc.setTextColor(...GRAY)
    doc.text('THE WELLNESS CO. · CLARITY Thermal Assessment', margin, pageH - 8)
    doc.text(`${pn}`, pageW - margin, pageH - 8, { align: 'right' })
    goldLine(pageH - 12, 0.3)
  }

  function newPage() {
    addPageFooter(pageNum)
    doc.addPage()
    pageNum++
    y = 25
  }

  function checkSpace(needed: number) {
    if (y + needed > pageH - 25) newPage()
  }

  // ════════════════════════════════════════
  // PAGE 1: COVER
  // ════════════════════════════════════════

  // Navy background
  doc.setFillColor(...PRIMARY)
  doc.rect(0, 0, pageW, pageH, 'F')

  // Gold accent line
  doc.setDrawColor(...GOLD)
  doc.setLineWidth(0.8)
  doc.line(margin, 50, margin + 40, 50)

  // Title
  doc.setFontSize(10)
  doc.setTextColor(...GOLD)
  doc.text('THE WELLNESS CO.', margin, 62)

  doc.setFontSize(28)
  doc.setTextColor(...WHITE)
  doc.text('CLARITY', margin, 80)
  doc.setFontSize(22)
  doc.text('Thermal Assessment', margin, 92)
  doc.text('Report', margin, 104)

  // Gold line below title
  doc.setDrawColor(...GOLD)
  doc.setLineWidth(0.5)
  doc.line(margin, 112, pageW - margin, 112)

  // Patient info
  doc.setFontSize(11)
  doc.setTextColor(...GOLD_LIGHT)
  doc.text('Prepared for', margin, 128)
  doc.setFontSize(16)
  doc.setTextColor(...WHITE)
  doc.text(session.patient_name, margin, 138)

  doc.setFontSize(10)
  doc.setTextColor(...GOLD_LIGHT)
  doc.text(`Assessment Date: ${fmtDate(session.session_date)}`, margin, 150)
  if (session.performed_by) {
    doc.text(`Performed by: ${session.performed_by}`, margin, 158)
  }

  // Summary stats
  y = 180
  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  doc.text(`${images.length} thermal views captured`, margin, y)
  doc.text(`${findings.length} findings identified`, margin, y + 8)

  const significantCount = findings.filter(f => f.severity === 'significant').length
  const moderateCount = findings.filter(f => f.severity === 'moderate').length
  if (significantCount > 0) {
    doc.setTextColor(...RED)
    doc.text(`${significantCount} significant finding${significantCount > 1 ? 's' : ''} requiring attention`, margin, y + 16)
  } else if (moderateCount > 0) {
    doc.setTextColor(...ORANGE)
    doc.text(`${moderateCount} moderate finding${moderateCount > 1 ? 's' : ''} to monitor`, margin, y + 16)
  }

  // Footer note
  doc.setFontSize(7)
  doc.setTextColor(...GRAY)
  doc.text('This report is generated by the CLARITY thermal assessment system and should', margin, pageH - 24)
  doc.text('be reviewed in conjunction with your provider for clinical interpretation.', margin, pageH - 19)

  addPageFooter(pageNum)

  // ════════════════════════════════════════
  // PAGE 2: THERMAL IMAGE GALLERY
  // ════════════════════════════════════════

  newPage()

  doc.setFontSize(16)
  doc.setTextColor(...PRIMARY)
  doc.text('Thermal Image Gallery', margin, y)
  y += 4
  goldLine(y)
  y += 10

  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  doc.text('False-color thermal images captured during your assessment. Warmer areas appear in brighter colors.', margin, y, { maxWidth: contentW })
  y += 14

  // 2x3 grid of images (placeholder rectangles with labels — actual images would need base64 embedding)
  const imgW = (contentW - 10) / 2
  const imgH = 55

  for (let i = 0; i < images.length; i++) {
    const col = i % 2
    const row = Math.floor(i / 2)
    const ix = margin + col * (imgW + 10)
    const iy = y + row * (imgH + 18)

    if (iy + imgH + 18 > pageH - 25) {
      newPage()
      continue
    }

    // Image placeholder
    doc.setFillColor(240, 240, 240)
    doc.roundedRect(ix, iy, imgW, imgH, 3, 3, 'F')

    // View label
    doc.setFontSize(10)
    doc.setTextColor(...PRIMARY)
    const viewLabel = VIEW_LABELS[images[i].view_type as ViewType] || images[i].view_type
    doc.text(viewLabel, ix, iy + imgH + 6)

    // Temperature range
    const img = images[i]
    if (img.min_temp_celsius !== null && img.max_temp_celsius !== null) {
      doc.setFontSize(8)
      doc.setTextColor(...GOLD)
      doc.text(
        `${img.min_temp_celsius.toFixed(1)}°C — ${img.max_temp_celsius.toFixed(1)}°C`,
        ix + imgW, iy + imgH + 6, { align: 'right' }
      )
    }

    // Placeholder text
    doc.setFontSize(8)
    doc.setTextColor(...GRAY)
    doc.text('[Thermal Image]', ix + imgW / 2, iy + imgH / 2, { align: 'center' })
  }

  // ════════════════════════════════════════
  // PAGE 3: KEY FINDINGS
  // ════════════════════════════════════════

  newPage()

  doc.setFontSize(16)
  doc.setTextColor(...PRIMARY)
  doc.text('Key Findings', margin, y)
  y += 4
  goldLine(y)
  y += 10

  if (findings.length === 0) {
    doc.setFontSize(11)
    doc.setTextColor(...SAGE)
    doc.text('No significant thermal anomalies detected. Your thermal profile appears within normal parameters.', margin, y, { maxWidth: contentW })
  } else {
    doc.setFontSize(9)
    doc.setTextColor(...GRAY)
    doc.text('The following thermal patterns were identified during your assessment:', margin, y, { maxWidth: contentW })
    y += 10

    for (const finding of findings) {
      checkSpace(40)

      // Severity badge
      const sevColor = SEVERITY_COLORS[finding.severity] || GOLD
      doc.setFillColor(sevColor[0], sevColor[1], sevColor[2])
      doc.roundedRect(margin, y, 3, 3, 1, 1, 'F')

      // Title
      doc.setFontSize(11)
      doc.setTextColor(...DARK_TEXT)
      doc.text(finding.title, margin + 8, y + 3)

      // Severity label
      doc.setFontSize(8)
      doc.setTextColor(sevColor[0], sevColor[1], sevColor[2])
      const sevText = finding.severity.charAt(0).toUpperCase() + finding.severity.slice(1)
      doc.text(sevText, pageW - margin, y + 3, { align: 'right' })

      y += 8

      // Description
      doc.setFontSize(9)
      doc.setTextColor(...GRAY)
      const descLines = doc.splitTextToSize(finding.description, contentW - 8)
      doc.text(descLines, margin + 8, y)
      y += descLines.length * 4 + 2

      // Temperature data
      if (finding.temperature_delta_celsius !== null) {
        doc.setFontSize(8)
        doc.setTextColor(...GOLD)
        let tempText = `Temperature difference: ${Math.abs(finding.temperature_delta_celsius).toFixed(1)}°C`
        if (finding.peak_temperature_celsius !== null) {
          tempText += ` | Peak: ${finding.peak_temperature_celsius.toFixed(1)}°C`
        }
        doc.text(tempText, margin + 8, y)
        y += 6
      }

      // Treatment recommendations
      if (finding.recommended_treatments?.length > 0) {
        doc.setFontSize(8)
        doc.setTextColor(...SAGE)
        for (const rec of finding.recommended_treatments) {
          checkSpace(6)
          const recName = typeof rec === 'string' ? rec : rec.name || ''
          doc.text(`→  ${recName}`, margin + 12, y)
          y += 4
        }
      }

      y += 6

      // Divider between findings
      doc.setDrawColor(...LIGHT_GRAY)
      doc.setLineWidth(0.2)
      doc.line(margin + 8, y, pageW - margin, y)
      y += 6
    }
  }

  // ════════════════════════════════════════
  // PAGE 4: RECOMMENDED PROTOCOLS
  // ════════════════════════════════════════

  newPage()

  doc.setFontSize(16)
  doc.setTextColor(...PRIMARY)
  doc.text('Recommended Protocols', margin, y)
  y += 4
  goldLine(y)
  y += 10

  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  doc.text('Based on your thermal assessment findings, the following protocols may support your wellness goals:', margin, y, { maxWidth: contentW })
  y += 14

  // Collect unique treatment recommendations
  const allTreatments = new Map<string, string[]>()
  for (const finding of findings) {
    for (const rec of (finding.recommended_treatments || [])) {
      const name = typeof rec === 'string' ? rec : rec.name
      const rationale = typeof rec === 'string' ? '' : rec.rationale || ''
      if (!allTreatments.has(name)) allTreatments.set(name, [])
      if (rationale && !allTreatments.get(name)!.includes(rationale)) {
        allTreatments.get(name)!.push(rationale)
      }
    }
  }

  const treatmentDescriptions: Record<string, string> = {
    'SoftWave Therapy': 'Acoustic wave technology that reduces inflammation at the cellular level, promotes blood flow, and activates your body\'s natural healing response. Non-invasive and FDA-cleared.',
    'IV Glutathione + Vitamin C': 'Powerful antioxidant infusion delivered directly to your bloodstream for maximum absorption. Supports systemic detoxification and reduces oxidative stress.',
    'IV Anti-Inflammatory Protocol': 'Targeted intravenous therapy combining anti-inflammatory compounds to address elevated inflammation markers throughout your body.',
    'BPC-157 Peptide Protocol': 'Body Protection Compound-157 is a naturally occurring peptide that accelerates tissue repair, reduces inflammation, and supports gut and musculoskeletal healing.',
    'BPC-157 / TB-500 Peptide Protocol': 'A synergistic peptide combination that promotes tissue regeneration, reduces inflammation, and supports recovery at the cellular level.',
    'Infrared Sauna': 'Deep-penetrating infrared heat that improves circulation, supports detoxification, reduces muscle tension, and promotes cellular recovery.',
  }

  for (const [name, rationales] of allTreatments) {
    checkSpace(35)

    // Treatment name
    doc.setFillColor(...GOLD_LIGHT)
    doc.roundedRect(margin, y, contentW, 8, 2, 2, 'F')
    doc.setFontSize(10)
    doc.setTextColor(...PRIMARY)
    doc.text(name, margin + 4, y + 5.5)
    y += 12

    // Description
    const desc = treatmentDescriptions[name] || rationales[0] || ''
    if (desc) {
      doc.setFontSize(9)
      doc.setTextColor(...GRAY)
      const lines = doc.splitTextToSize(desc, contentW - 8)
      doc.text(lines, margin + 4, y)
      y += lines.length * 4 + 4
    }

    // Connection to findings
    if (rationales.length > 0) {
      doc.setFontSize(8)
      doc.setTextColor(...SAGE)
      for (const r of rationales.slice(0, 2)) {
        const rLines = doc.splitTextToSize(`Based on your results: ${r}`, contentW - 12)
        doc.text(rLines, margin + 8, y)
        y += rLines.length * 3.5 + 2
      }
    }

    y += 6
  }

  // ════════════════════════════════════════
  // PAGE 5: YOUR NEXT STEP
  // ════════════════════════════════════════

  newPage()

  doc.setFontSize(16)
  doc.setTextColor(...PRIMARY)
  doc.text('Your Next Step', margin, y)
  y += 4
  goldLine(y)
  y += 12

  doc.setFontSize(10)
  doc.setTextColor(...DARK_TEXT)
  doc.text('This thermal assessment provides a window into your body\'s', margin, y)
  y += 5
  doc.text('inflammatory patterns and circulatory health.', margin, y)
  y += 10

  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  const nextStepText = 'Your provider will review these findings with you and create a personalized protocol that addresses the patterns identified. Thermal imaging is most powerful when combined with lab work, clinical assessment, and longitudinal tracking over time.'
  const nsLines = doc.splitTextToSize(nextStepText, contentW)
  doc.text(nsLines, margin, y)
  y += nsLines.length * 4 + 12

  // Contact card
  doc.setFillColor(...GOLD_LIGHT)
  doc.roundedRect(margin, y, contentW, 35, 3, 3, 'F')
  y += 8

  doc.setFontSize(11)
  doc.setTextColor(...PRIMARY)
  doc.text('Schedule Your Follow-Up', margin + 10, y)
  y += 7

  doc.setFontSize(9)
  doc.setTextColor(...GRAY)
  doc.text('THE WELLNESS CO.', margin + 10, y)
  y += 5
  doc.text('(619) 444-3264  |  urwellness.co', margin + 10, y)
  y += 5
  doc.text('Santee, San Diego, CA', margin + 10, y)

  addPageFooter(pageNum)

  // Return buffer
  return Buffer.from(doc.output('arraybuffer'))
}
